routes/web.php
<?php

use App\Http\Controllers\AnnonceController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource("annonce", AnnonceController::class);

app/Models/Annonce.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Annonce extends Model
{
    use HasFactory;
    protected $guarded=[];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AnnonceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Annonce;
use App\Http\Requests\AnnonceRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class AnnonceController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
       $annonces=Annonce::all();
       return view("annonce.index", compact("annonces"));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view("annonce.create");
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(AnnonceRequest $request)
    {   
        $data=$request->all();
        if($request->has("photo")){
              $photo=$request->photo;
              $nameOfPhoto=$photo->store("photos");
              $data["photo"]= $nameOfPhoto;
        }
      

       Annonce::create($data);
       return redirect()->route("annonce.index")->with("success", "L'ajout de la nouvelle annonce a bien réussi!");
    }

    /**
     * Display the specified resource.
     */
    public function show(Annonce $annonce)
    {
       return view("annonce.show", compact("annonce"));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Annonce $annonce)
    {
        return view("annonce.edit", compact("annonce"));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(AnnonceRequest $request, Annonce $annonce)
    {
        $data=$request->all();
        if($request->has("photo")){
            $photo=$request->photo;
            $nameOfPhoto=$photo->store("photos");

            $data["photo"]= $nameOfPhoto;
        }
        else{
            $data["photo"]=$annonce->photo;
        }

        $annonce->update($data);
         return redirect()->route("annonce.index")->with("success", "La modification a bien réussi!");

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Annonce $annonce)
    {
           $annonce->delete();
           return redirect()->route("annonce.index")->with("success", "La suppression a bien réussi!");

    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

resources/views/annonce/create.blade.php
@extends("template.master")
@section("titre", "Liste des annonces")
@section("contenu")
     <h1 class="mt-2 mb-2">Nouvelle annonce</h1>   

     @if($errors->any()) 
     <ul class="alert alert-danger">
       
        @foreach($errors->all() as $error)
           <li>{{ $error }}</li>       
        @endforeach 
    </ul>
     @endif
    <form method="post" action="{{ route('annonce.store')}}"  class="w-50" enctype="multipart/form-data" >
        @csrf
        <div class="mb-3">
        <label for="titre" class="form-label">Titre</label>
        <input type="text" class="form-control" id="titre" name="titre">
        </div>

        <div class="mb-3">
        <label for="description" class="form-label">Description</label>
        <input type="text" class="form-control" id="description" name="description">
        </div>

    
      
        <div class="mb-3">
        <label for="type" class="form-label">Type</label>
        <select class="form-select" name="type">
                <option selected>Veuillez choisir un type</option>
                <option value="Appartement">Appartement</option>
                <option value="Maison">Maison</option>
                <option value="Villa">Villa</option>
                <option value="Magasin">Magasin</option>
                <option value="Terrain">Terrain</option>
         </select> </div>

        <div class="mb-3">
        <label for="ville" class="form-label">Ville</label>
        <input type="text" class="form-control" id="ville" name="ville">
        </div>

        <div class="mb-3">
        <label for="superficie" class="form-label">Superficie</label>
        <input type="text" class="form-control" id="superficie" name="superficie">
        </div>

        <div class="mb-3 form-check-inline">
        <label class="form-label ">Etat</label><br>
         <input type="radio" id="neuf" name="neuf" value="1">Neuf &nbsp;
         <input type="radio" id="neuf" name="neuf"value='0'> Ancien
        </div>

        <div class="mb-3">
        <label for="prix" class="form-label">Prix</label>
        <input type="text" class="form-control" id="prix" name="prix">
        </div>
    <div class="mb-3">
        <label for="photo" class="form-label">Photo</label>
        <input type="file" class="form-control" id="photo" name="photo">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

resources/views/annonce/edit.blade.php
@extends("template.master")
@section("titre", "Liste des annonces")
@section("contenu")
    @isset($annonce)
      <h1 class="mt-2 mb-2">Mise à jour de l'annonce numero {{$annonce->id}} </h1>   
  @if($errors->any()) 
     <ul class="alert alert-danger">
       
        @foreach($errors->all() as $error)
           <li>{{ $error }}</li>       
        @endforeach 
    </ul>
     @endif
    <form method="post" action="{{ route('annonce.update', $annonce->id)}}"  class="w-50" enctype="multipart/form-data" >
        @csrf
        @method("PUT")
        <div class="mb-3">
        <label for="titre" class="form-label">Titre</label>
        <input type="text" class="form-control" id="titre" name="titre" value="{{ $annonce->titre }}">
        </div>

        <div class="mb-3">
        <label for="description" class="form-label">Description</label>
        <input type="text" class="form-control" id="description" name="description" value="{{ $annonce->description }}">
        </div>

    
      
        <div class="mb-3">
        <label for="type" class="form-label">Type</label>
        <select class="form-select" name="type">
                <option selected>Veuillez choisir un type</option>
                <option value="Appartement"  {{ $annonce->type=='Appartement'? "selected": "" }} >Appartement</option>
                <option value="Maison" {{ $annonce->type=='Maison'? "selected": "" }} >Maison</option>
                <option value="Villa" {{ $annonce->type=='Villa'? "selected": "" }} >Villa</option>
                <option value="Magasin" {{ $annonce->type=='Magasin'? "selected": "" }} >Magasin</option>
                <option value="Terrain" {{ $annonce->type=='Terrain'? "selected": "" }} >Terrain</option>
         </select> </div>

        <div class="mb-3">
        <label for="ville" class="form-label">Ville</label>
        <input type="text" class="form-control" id="ville" name="ville" value="{{ $annonce->ville }}">
        </div>

        <div class="mb-3">
        <label for="superficie" class="form-label">Superficie</label>
        <input type="text" class="form-control" id="superficie" name="superficie" value="{{ $annonce->superficie }}">
        </div>

        <div class="mb-3 form-check-inline">
        <label class="form-label ">Etat</label><br>
         <input type="radio" id="neuf" name="neuf" value="1"   {{ $annonce->neuf? "checked": "" }} >Neuf &nbsp;
         <input type="radio" id="neuf" name="neuf" value='0'  {{ $annonce->neuf? "": "checked" }}> Ancien
        </div>

        <div class="mb-3">
        <label for="prix" class="form-label">Prix</label>
        <input type="text" class="form-control" id="prix" name="prix" value="{{ $annonce->prix }}">
        </div>
 <div class="mb-3">
       @if(isset($annonce->photo))
            <img src="{{asset($annonce->photo)}}" alt="" width="300px">
        @else
        <span>Aucune photo n'est ajoutée pour cette annonce</span>
       @endif
        <input type="file" class="form-control" id="photo" name="photo">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    @endisset
@endsection

resources/views/annonce/index.blade.php
@extends("template.master")
@section("titre", "Liste des annonces")
@section("contenu")
<h2 class="mt-2">Liste des annonces</h2>
<a href="{{ route('annonce.create') }}" class="btn btn-primary mt-2 mb-3">Nouvelle annonce</a>
    @if(session()->has("success"))    
    <div class="alert alert-success">
        {{session("success")}}
    </div>  
    @endif
@isset($annonces)
        <table class="table">
            <tr>
                <th>Photo</th>
                <th>Titre</th>
                <th>Description</th>
                <th>Type</th>
                <th>Ville</th>
                <th>Superficie (m<sup>2</sup>)</th>
                <th>Etat</th>
                <th>Prix (dhs)</th>
                <th>Actions</th>
            </tr>
            @foreach($annonces as $annonce)
                <tr>
                    <td>
                        @if(isset($annonce->photo))
                            <img src="{{ asset($annonce->photo) }}" alt="" width="80px">
                        @else
                            <img src="{{ asset('photos/default.png') }}" alt="" width="80px">
                        @endif
                    </td>
                    <td>{{ $annonce->titre }}</td>
                    <td>{{ $annonce->description }}</td>
                    <td>{{ $annonce->type }}</td>
                    <td>{{ $annonce->ville }}</td>
                    <td>{{ $annonce->superficie }}</td>
                    <td>{{ ($annonce->neuf)? "Neuf":"Ancien" }}</td>
                    <td>{{ $annonce->prix }}</td>
                    <td>
                        <form action="{{ route('annonce.destroy',  $annonce->id ) }}" method="post">
                            @csrf
                            @method("DELETE")
                            <a href="{{ route('annonce.edit',  $annonce->id ) }}" ><i class="bi bi-pencil text-success p-1"></i></a>
                            <a href="{{ route('annonce.show',  $annonce->id ) }}" > <i class="bi bi-eye text-secondary p-1"></i></a>
                            <button type="submit" class="btn border-none p-1"
                            onclick="return confirm('Voulez vous supprimer {{ $annonce->titre }}?')"
                            > <i class="bi bi-trash2 text-danger" style="font-size:20px"></i></button>
                        </form>
                    </td>
                </tr>
            @endforeach
           
        </table>
    @endisset
@endsection

resources/views/annonce/show.blade.php
@extends("template.master")
@section("titre", "Liste des annonces")
@section("contenu")
    @isset($annonce)
        <h2>Détails de l'annonce numéro {{ $annonce->id }}</h2>
             @if(isset($annonce->photo))
                            <img src="{{ asset($annonce->photo) }}" alt="" width="500px">
                        @else
                            <img src="{{ asset('photos/default.png') }}" alt="" width="500px">
                        @endif <br>
        Titre:  {{ $annonce->titre }} <br>
        Description:  {{ $annonce->description }} <br>
        Etat:  {{ $annonce->neuf? "Neuf":"Ancien" }}
    @endisset
@endsection

resources/views/template/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield("titre")</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
</head>
<body>
    <div class="container">
         @yield("contenu")
    </div>
   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>